# Generated by Django 5.2.4 on 2026-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Descripcion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Portada'),
        ),
    ]
