# Generated by Django 5.2.4 on 2026-07-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_categoria_descripcion_libro_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='Desconocida', max_length=20),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='codigo',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
