# Generated by Django 5.2.4 on 2026-07-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_libro_id_libro_editorial_libro_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
